import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { attachmentBucket, DeleteObjectCommand, GetObjectCommand, objectStorage, PutObjectCommand } from "@/lib/object-storage";
import { prisma } from "@/lib/prisma";
import { canWrite, projectAccess } from "@/lib/permissions";
import { readWorkspaceSettings } from "@/lib/workspace-settings";

const maxBytes = Number(process.env.MAX_ATTACHMENT_BYTES || 10 * 1024 * 1024);
const safe = (value: string) => value.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 180) || "attachment";
async function accessFor(userId: string, projectId: string, module: string, recordId: string) { const access = await projectAccess(userId, projectId); if (!access || !["bom", "tests"].includes(module)) return null; const record = module === "bom" ? await prisma.bomItem.findFirst({ where: { id: recordId, projectId, deletedAt: null } }) : await prisma.testRecord.findFirst({ where: { id: recordId, projectId, deletedAt: null } }); return record ? { access, record } : null; }
export async function GET(request: Request, { params }: { params: Promise<{ id: string; module: string; recordId: string }> }) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { id, module, recordId } = await params; const result = await accessFor(session.user.id, id, module, recordId); if (!result) return NextResponse.json({ error: "Not found" }, { status: 404 }); const attachmentId = new URL(request.url).searchParams.get("attachmentId"); if (!attachmentId) return NextResponse.json(await prisma.attachment.findMany({ where: module === "bom" ? { bomItemId: recordId, deletedAt: null } : { testRecordId: recordId, deletedAt: null }, select: { id: true, filename: true, mimeType: true, size: true, createdAt: true }, orderBy: { createdAt: "desc" } })); const attachment = await prisma.attachment.findFirst({ where: { id: attachmentId, deletedAt: null, ...(module === "bom" ? { bomItemId: recordId } : { testRecordId: recordId }) } }); if (!attachment) return NextResponse.json({ error: "Not found" }, { status: 404 }); try { const object = await objectStorage.send(new GetObjectCommand({ Bucket: attachmentBucket, Key: attachment.storageKey })); if (!object.Body) throw new Error(); return new NextResponse(object.Body.transformToWebStream(), { headers: { "Content-Type": attachment.mimeType, "Content-Disposition": `attachment; filename*=UTF-8''${encodeURIComponent(attachment.filename)}`, "Cache-Control": "private, no-store" } }); } catch { return NextResponse.json({ error: "附件資料無法讀取" }, { status: 404 }); } }
export async function POST(request: Request, { params }: { params: Promise<{ id: string; module: string; recordId: string }> }) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { id, module, recordId } = await params; const result = await accessFor(session.user.id, id, module, recordId); if (!result || !canWrite(result.access.membership.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const file = (await request.formData()).get("file"); if (!(file instanceof File) || !file.size || file.size > maxBytes) return NextResponse.json({ error: "附件檔案不正確或超過大小限制" }, { status: 400 }); if (!(await readWorkspaceSettings(result.access.project.workspaceId)).security.attachmentsEnabled) return NextResponse.json({ error: "管理者已停用附件上傳" }, { status: 403 }); const storageKey = `${id}/${module}-${recordId}/${crypto.randomUUID()}-${safe(file.name)}`; try { await objectStorage.send(new PutObjectCommand({ Bucket: attachmentBucket, Key: storageKey, Body: Buffer.from(await file.arrayBuffer()), ContentType: file.type || "application/octet-stream" })); const attachment = await prisma.attachment.create({ data: { filename: file.name, mimeType: file.type || "application/octet-stream", size: file.size, storageKey, ...(module === "bom" ? { bomItemId: recordId } : { testRecordId: recordId }) } }); return NextResponse.json(attachment, { status: 201 }); } catch { try { await objectStorage.send(new DeleteObjectCommand({ Bucket: attachmentBucket, Key: storageKey })); } catch {} return NextResponse.json({ error: "附件上傳失敗" }, { status: 502 }); } }
export async function DELETE(request: Request, { params }: { params: Promise<{ id: string; module: string; recordId: string }> }) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { id, module, recordId } = await params; const result = await accessFor(session.user.id, id, module, recordId); if (!result || !canWrite(result.access.membership.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const attachmentId = new URL(request.url).searchParams.get("attachmentId"); if (!attachmentId) return NextResponse.json({ error: "attachmentId required" }, { status: 400 }); const updated = await prisma.attachment.updateMany({ where: { id: attachmentId, ...(module === "bom" ? { bomItemId: recordId } : { testRecordId: recordId }), deletedAt: null }, data: { deletedAt: new Date(), deletionBatchId: crypto.randomUUID() } }); return updated.count ? NextResponse.json({ ok: true }) : NextResponse.json({ error: "Not found" }, { status: 404 }); }
