import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { attachmentBucket, GetObjectCommand, objectStorage } from "@/lib/object-storage";
import { enqueueAttachmentUpload, processAttachmentSyncJob } from "@/lib/attachment-sync";
import { prisma } from "@/lib/prisma";
import { canWrite, projectAccess } from "@/lib/permissions";
import { readWorkspaceSettings } from "@/lib/workspace-settings";
import { inspectUploadedFile } from "@/lib/file-signature";

const maxBytes = Number(process.env.MAX_ATTACHMENT_BYTES || 10 * 1024 * 1024);
const allowedMimeTypes = new Set((process.env.ALLOWED_ATTACHMENT_MIME_TYPES || "").split(",").map((type) => type.trim()).filter(Boolean));
const safe = (value: string) => value.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 180) || "attachment";
async function accessFor(userId: string, projectId: string, module: string, recordId: string) { const access = await projectAccess(userId, projectId); if (!access || !["bom", "tests"].includes(module)) return null; const record = module === "bom" ? await prisma.bomItem.findFirst({ where: { id: recordId, projectId, deletedAt: null } }) : await prisma.testRecord.findFirst({ where: { id: recordId, projectId, deletedAt: null } }); return record ? { access, record } : null; }
export async function GET(request: Request, { params }: { params: Promise<{ id: string; module: string; recordId: string }> }) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { id, module, recordId } = await params; const result = await accessFor(session.user.id, id, module, recordId); if (!result) return NextResponse.json({ error: "Not found" }, { status: 404 }); const attachmentId = new URL(request.url).searchParams.get("attachmentId"); if (!attachmentId) return NextResponse.json(await prisma.attachment.findMany({ where: module === "bom" ? { bomItemId: recordId, deletedAt: null } : { testRecordId: recordId, deletedAt: null }, select: { id: true, filename: true, mimeType: true, size: true, createdAt: true, syncStatus: true }, orderBy: { createdAt: "desc" } })); const attachment = await prisma.attachment.findFirst({ where: { id: attachmentId, deletedAt: null, ...(module === "bom" ? { bomItemId: recordId } : { testRecordId: recordId }) } }); if (!attachment) return NextResponse.json({ error: "Not found" }, { status: 404 }); if (attachment.syncStatus !== "READY") return NextResponse.json({ error: "附件仍在同步中" }, { status: 409 }); try { const object = await objectStorage.send(new GetObjectCommand({ Bucket: attachmentBucket, Key: attachment.storageKey })); if (!object.Body) throw new Error(); return new NextResponse(object.Body.transformToWebStream(), { headers: { "Content-Type": attachment.mimeType, "Content-Disposition": `attachment; filename*=UTF-8''${encodeURIComponent(attachment.filename)}`, "Cache-Control": "private, no-store" } }); } catch { return NextResponse.json({ error: "附件資料無法讀取" }, { status: 404 }); } }
export async function POST(request: Request, { params }: { params: Promise<{ id: string; module: string; recordId: string }> }) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { id, module, recordId } = await params; const result = await accessFor(session.user.id, id, module, recordId); if (!result || !canWrite(result.access.membership.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const file = (await request.formData()).get("file"); if (!(file instanceof File) || !file.size || !Number.isFinite(maxBytes) || maxBytes <= 0 || file.size > maxBytes) return NextResponse.json({ error: "附件檔案不正確、超過大小限制，或伺服器附件設定無效" }, { status: 400 }); if (!(await readWorkspaceSettings(result.access.project.workspaceId)).security.attachmentsEnabled) return NextResponse.json({ error: "管理者已停用附件上傳" }, { status: 403 }); const storageKey = `${id}/${module}-${recordId}/${crypto.randomUUID()}-${safe(file.name)}`; const payload = Buffer.from(await file.arrayBuffer()); let upload; try { upload = inspectUploadedFile(payload, file.type); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "無法驗證檔案內容" }, { status: 415 }); } if (allowedMimeTypes.size && !allowedMimeTypes.has(upload.mimeType)) return NextResponse.json({ error: "此附件類型不被允許" }, { status: 415 }); const attachment = await prisma.$transaction(async (tx) => { const created = await tx.attachment.create({ data: { filename: file.name, mimeType: upload.mimeType, size: file.size, storageKey, ...(module === "bom" ? { bomItemId: recordId } : { testRecordId: recordId }) } }); await enqueueAttachmentUpload(tx, created.id, payload); await tx.auditEvent.create({ data: { action: "record_attachment.upload_queued", entity: "attachment", entityId: created.id, userId: session.user.id, workspaceId: result.access.project.workspaceId, projectId: id, metadata: { module, recordId, filename: created.filename, size: created.size } } }); return created; }); await processAttachmentSyncJob(attachment.id); const synced = await prisma.attachment.findUnique({ where: { id: attachment.id } }); return NextResponse.json(synced || attachment, { status: synced?.syncStatus === "READY" ? 201 : 202 }); }
export async function DELETE(request: Request, { params }: { params: Promise<{ id: string; module: string; recordId: string }> }) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { id, module, recordId } = await params; const result = await accessFor(session.user.id, id, module, recordId); if (!result || !canWrite(result.access.membership.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const attachmentId = new URL(request.url).searchParams.get("attachmentId"); if (!attachmentId) return NextResponse.json({ error: "attachmentId required" }, { status: 400 }); const deletionBatchId = crypto.randomUUID(); const updated = await prisma.attachment.updateMany({ where: { id: attachmentId, ...(module === "bom" ? { bomItemId: recordId } : { testRecordId: recordId }), deletedAt: null }, data: { deletedAt: new Date(), deletionBatchId } }); if (!updated.count) return NextResponse.json({ error: "Not found" }, { status: 404 }); await prisma.auditEvent.create({ data: { action: "record_attachment.trashed", entity: "attachment", entityId: attachmentId, userId: session.user.id, workspaceId: result.access.project.workspaceId, projectId: id, metadata: { module, recordId, deletionBatchId } } }); return NextResponse.json({ ok: true }); }
