-- Baseline for installations created before Prisma migrations were introduced.
CREATE SCHEMA IF NOT EXISTS "public";
CREATE TYPE "WorkspaceRole" AS ENUM ('OWNER', 'ADMIN', 'EDITOR', 'VIEWER');
CREATE TYPE "TaskStatus" AS ENUM ('BACKLOG', 'TODO', 'IN_PROGRESS', 'BLOCKED', 'DONE');
CREATE TYPE "IssueStatus" AS ENUM ('OPEN', 'INVESTIGATING', 'RESOLVED', 'WONT_FIX');
CREATE TYPE "TestOutcome" AS ENUM ('PLANNED', 'PASS', 'FAIL', 'BLOCKED');
CREATE TYPE "DatabasePropertyType" AS ENUM ('TEXT', 'NUMBER', 'SELECT', 'MULTI_SELECT', 'STATUS', 'DATE', 'PERSON', 'FILES', 'CHECKBOX', 'URL', 'EMAIL', 'PHONE', 'RELATION', 'ROLLUP', 'FORMULA', 'UNIQUE_ID', 'CREATED_TIME', 'UPDATED_TIME');
CREATE TYPE "DatabaseViewLayout" AS ENUM ('TABLE', 'BOARD', 'CALENDAR', 'TIMELINE', 'GALLERY', 'LIST', 'FORM');
CREATE TYPE "AutomationTrigger" AS ENUM ('ROW_CREATED', 'ROW_UPDATED');
CREATE TYPE "AutomationAction" AS ENUM ('SET_PROPERTY', 'CREATE_ROW', 'NOTIFY');

CREATE TABLE "User" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "name" TEXT NOT NULL, "avatarEmoji" TEXT, "passwordHash" TEXT NOT NULL, "mustChangePassword" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Workspace" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Workspace_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Membership" ("id" TEXT NOT NULL, "role" "WorkspaceRole" NOT NULL DEFAULT 'VIEWER', "nickname" TEXT, "teamGroup" TEXT, "jobTitle" TEXT, "userId" TEXT NOT NULL, "workspaceId" TEXT NOT NULL, CONSTRAINT "Membership_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Project" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "code" TEXT NOT NULL, "description" TEXT, "workspaceId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Project_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Database" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "icon" TEXT NOT NULL DEFAULT '▦', "projectId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Database_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DatabaseProperty" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "type" "DatabasePropertyType" NOT NULL DEFAULT 'TEXT', "options" JSONB, "position" INTEGER NOT NULL DEFAULT 0, "databaseId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "DatabaseProperty_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DatabaseView" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "layout" "DatabaseViewLayout" NOT NULL DEFAULT 'TABLE', "config" JSONB, "filter" JSONB, "sort" JSONB, "position" INTEGER NOT NULL DEFAULT 0, "databaseId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "DatabaseView_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DatabaseTemplate" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "values" JSONB NOT NULL DEFAULT '{}', "databaseId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "DatabaseTemplate_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DatabaseAutomation" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "trigger" "AutomationTrigger" NOT NULL, "action" "AutomationAction" NOT NULL, "config" JSONB NOT NULL DEFAULT '{}', "enabled" BOOLEAN NOT NULL DEFAULT true, "databaseId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "DatabaseAutomation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DatabaseRow" ("id" TEXT NOT NULL, "values" JSONB NOT NULL DEFAULT '{}', "position" INTEGER NOT NULL DEFAULT 0, "databaseId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "DatabaseRow_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Document" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "icon" TEXT NOT NULL DEFAULT '📄', "content" JSONB NOT NULL DEFAULT '{"type":"doc","content":[{"type":"paragraph"}]}', "position" INTEGER NOT NULL DEFAULT 0, "projectId" TEXT NOT NULL, "parentId" TEXT, "deletedAt" TIMESTAMP(3), "deletionBatchId" TEXT, "updatedAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Document_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DocumentComment" ("id" TEXT NOT NULL, "body" TEXT NOT NULL, "resolvedAt" TIMESTAMP(3), "documentId" TEXT NOT NULL, "authorId" TEXT NOT NULL, "parentId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "DocumentComment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DocumentRevision" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "content" JSONB NOT NULL, "markdown" TEXT, "documentId" TEXT NOT NULL, "authorId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DocumentRevision_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "body" TEXT, "href" TEXT, "readAt" TIMESTAMP(3), "userId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Task" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "status" "TaskStatus" NOT NULL DEFAULT 'TODO', "priority" INTEGER NOT NULL DEFAULT 2, "startDate" TIMESTAMP(3), "dueDate" TIMESTAMP(3), "projectId" TEXT NOT NULL, "assigneeId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Task_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Issue" ("id" TEXT NOT NULL, "key" TEXT NOT NULL, "title" TEXT NOT NULL, "status" "IssueStatus" NOT NULL DEFAULT 'OPEN', "severity" INTEGER NOT NULL DEFAULT 2, "projectId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Issue_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BomItem" ("id" TEXT NOT NULL, "partNumber" TEXT NOT NULL, "name" TEXT NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "unitCost" DECIMAL(12,2), "supplier" TEXT, "status" TEXT NOT NULL DEFAULT 'PLANNED', "projectId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BomItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TestRecord" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "outcome" "TestOutcome" NOT NULL DEFAULT 'PLANNED', "testDate" TIMESTAMP(3), "operator" TEXT, "notes" TEXT, "projectId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TestRecord_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Attachment" ("id" TEXT NOT NULL, "filename" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "size" INTEGER NOT NULL, "storageKey" TEXT NOT NULL, "documentId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Attachment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditEvent" ("id" TEXT NOT NULL, "action" TEXT NOT NULL, "entity" TEXT NOT NULL, "entityId" TEXT NOT NULL, "metadata" JSONB, "userId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditEvent_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Workspace_slug_key" ON "Workspace"("slug");
CREATE INDEX "Membership_workspaceId_role_idx" ON "Membership"("workspaceId", "role");
CREATE UNIQUE INDEX "Membership_userId_workspaceId_key" ON "Membership"("userId", "workspaceId");
CREATE UNIQUE INDEX "Project_workspaceId_code_key" ON "Project"("workspaceId", "code");
CREATE INDEX "Database_projectId_createdAt_idx" ON "Database"("projectId", "createdAt");
CREATE INDEX "DatabaseProperty_databaseId_position_idx" ON "DatabaseProperty"("databaseId", "position");
CREATE INDEX "DatabaseView_databaseId_position_idx" ON "DatabaseView"("databaseId", "position");
CREATE UNIQUE INDEX "DatabaseTemplate_databaseId_name_key" ON "DatabaseTemplate"("databaseId", "name");
CREATE INDEX "DatabaseAutomation_databaseId_enabled_idx" ON "DatabaseAutomation"("databaseId", "enabled");
CREATE INDEX "DatabaseRow_databaseId_position_idx" ON "DatabaseRow"("databaseId", "position");
CREATE INDEX "Document_projectId_parentId_position_idx" ON "Document"("projectId", "parentId", "position");
CREATE INDEX "Document_projectId_deletedAt_idx" ON "Document"("projectId", "deletedAt");
CREATE INDEX "Document_deletionBatchId_idx" ON "Document"("deletionBatchId");
CREATE INDEX "DocumentComment_documentId_resolvedAt_createdAt_idx" ON "DocumentComment"("documentId", "resolvedAt", "createdAt");
CREATE INDEX "DocumentRevision_documentId_createdAt_idx" ON "DocumentRevision"("documentId", "createdAt");
CREATE INDEX "Notification_userId_readAt_createdAt_idx" ON "Notification"("userId", "readAt", "createdAt");
CREATE INDEX "Task_projectId_status_idx" ON "Task"("projectId", "status");
CREATE UNIQUE INDEX "Issue_projectId_key_key" ON "Issue"("projectId", "key");
CREATE UNIQUE INDEX "BomItem_projectId_partNumber_key" ON "BomItem"("projectId", "partNumber");
CREATE INDEX "TestRecord_projectId_outcome_idx" ON "TestRecord"("projectId", "outcome");
CREATE UNIQUE INDEX "Attachment_storageKey_key" ON "Attachment"("storageKey");
CREATE INDEX "AuditEvent_entity_entityId_createdAt_idx" ON "AuditEvent"("entity", "entityId", "createdAt");

ALTER TABLE "Membership" ADD CONSTRAINT "Membership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Database" ADD CONSTRAINT "Database_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DatabaseProperty" ADD CONSTRAINT "DatabaseProperty_databaseId_fkey" FOREIGN KEY ("databaseId") REFERENCES "Database"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DatabaseView" ADD CONSTRAINT "DatabaseView_databaseId_fkey" FOREIGN KEY ("databaseId") REFERENCES "Database"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DatabaseTemplate" ADD CONSTRAINT "DatabaseTemplate_databaseId_fkey" FOREIGN KEY ("databaseId") REFERENCES "Database"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DatabaseAutomation" ADD CONSTRAINT "DatabaseAutomation_databaseId_fkey" FOREIGN KEY ("databaseId") REFERENCES "Database"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DatabaseRow" ADD CONSTRAINT "DatabaseRow_databaseId_fkey" FOREIGN KEY ("databaseId") REFERENCES "Database"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Document" ADD CONSTRAINT "Document_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Document" ADD CONSTRAINT "Document_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "Document"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "DocumentComment" ADD CONSTRAINT "DocumentComment_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentComment" ADD CONSTRAINT "DocumentComment_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentComment" ADD CONSTRAINT "DocumentComment_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "DocumentComment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentRevision" ADD CONSTRAINT "DocumentRevision_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentRevision" ADD CONSTRAINT "DocumentRevision_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Issue" ADD CONSTRAINT "Issue_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BomItem" ADD CONSTRAINT "BomItem_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TestRecord" ADD CONSTRAINT "TestRecord_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Attachment" ADD CONSTRAINT "Attachment_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
