"use client";

import { useEffect, useState } from "react";

type Comment = { id: string; body: string; resolvedAt: string | null; createdAt: string; author: { name: string } };
type Revision = { id: string; title: string; createdAt: string; author: { name: string } | null };

export function DocumentCollaborationPanel({ documentId, canWrite }: { documentId: string; canWrite: boolean }) {
  const [mode, setMode] = useState<"comments" | "history" | null>(null); const [comments, setComments] = useState<Comment[]>([]); const [revisions, setRevisions] = useState<Revision[]>([]); const [body, setBody] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { if (!mode) return; const endpoint = mode === "comments" ? "comments" : "revisions"; fetch(`/api/documents/${documentId}/${endpoint}`).then((response) => response.ok ? response.json() : []).then(mode === "comments" ? setComments : setRevisions); }, [documentId, mode]);
  async function addComment() { if (!body.trim()) return; const response = await fetch(`/api/documents/${documentId}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body }) }); if (!response.ok) return setMessage("留言尚未儲存"); const comment = await response.json(); setComments((current) => [...current, comment]); setBody(""); setMessage("已留言"); }
  async function restore(revisionId: string) { if (!window.confirm("要還原至此版本嗎？目前內容會保留在版本紀錄中。")) return; const response = await fetch(`/api/documents/${documentId}/revisions/${revisionId}/restore`, { method: "POST" }); if (!response.ok) return setMessage("無法還原版本"); window.location.reload(); }
  return <section className="document-collab"><div><button className={mode === "comments" ? "active" : ""} onClick={() => setMode(mode === "comments" ? null : "comments")}>💬 留言</button><button className={mode === "history" ? "active" : ""} onClick={() => setMode(mode === "history" ? null : "history")}>◷ 歷史版本</button></div>{mode === "comments" && <div className="collab-panel"><div className="comment-list">{comments.length ? comments.map((comment) => <article key={comment.id}><strong>{comment.author.name}</strong><time>{new Date(comment.createdAt).toLocaleString()}</time><p>{comment.body}</p></article>) : <p className="hint">尚無留言。用留言保留工程決策與待確認事項。</p>}</div>{canWrite ? <><textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="留下留言，使用 @姓名 提及同事" /><button className="collab-primary" onClick={addComment}>新增留言</button></> : <p className="hint">你目前為檢視者，只能閱讀留言。</p>}</div>}{mode === "history" && <div className="collab-panel revision-list">{revisions.length ? revisions.map((revision) => <article key={revision.id}><div><strong>{revision.title}</strong><span>{revision.author?.name || "未知使用者"} · {new Date(revision.createdAt).toLocaleString()}</span></div>{canWrite && <button onClick={() => restore(revision.id)}>還原</button>}</article>) : <p className="hint">第一次儲存後，版本歷史會自動建立。</p>}</div>}{message && <span className="collab-notice">{message}</span>}</section>;
}
