"use client";

import { useEffect, useState } from "react";

type Backlink = { id: string; title: string; icon: string; updatedAt: string };
type Workflow = { properties: Record<string, string>; reviewState: "DRAFT" | "IN_REVIEW" | "APPROVED" | "CHANGES_REQUESTED"; reviewRequestedAt: string | null; reviewedAt: string | null; lockedAt: string | null; lockedById: string | null; lockedBy: { name: string } | null; reviewer: { name: string } | null; canManage: boolean; canWrite: boolean; isLockedByMe: boolean };
const reviewLabels = { DRAFT: "草稿", IN_REVIEW: "審核中", APPROVED: "已核准", CHANGES_REQUESTED: "要求修改" };

export function DocumentWorkflowPanel({ documentId, projectId, canWrite }: { documentId: string; projectId: string; canWrite: boolean }) {
  const [workflow, setWorkflow] = useState<Workflow | null>(null); const [backlinks, setBacklinks] = useState<Backlink[]>([]); const [open, setOpen] = useState(false); const [notice, setNotice] = useState("");
  const load = async () => { const [workflowResponse, linksResponse] = await Promise.all([fetch(`/api/documents/${documentId}/workflow`, { cache: "no-store" }), fetch(`/api/documents/${documentId}/backlinks`, { cache: "no-store" })]); if (workflowResponse.ok) setWorkflow(await workflowResponse.json()); if (linksResponse.ok) setBacklinks(await linksResponse.json()); };
  useEffect(() => { if (open) void load(); }, [documentId, open]);
  async function action(action: "lock" | "unlock" | "request_review" | "approve" | "changes_requested" | "update_properties", properties?: Record<string, string>) { const response = await fetch(`/api/documents/${documentId}/workflow`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, properties }) }); const result = await response.json(); if (!response.ok) return setNotice(result.error || "無法更新文件工作流程"); setWorkflow(result); setNotice(action === "update_properties" ? "頁面屬性已儲存" : "文件工作流程已更新"); }
  function editProperties() { const next = { ...(workflow?.properties || {}) }; const key = window.prompt("屬性名稱，例如：文件狀態"); if (!key?.trim()) return; const value = window.prompt(`「${key.trim()}」的值`, next[key.trim()] || ""); if (value === null) return; next[key.trim()] = value; void action("update_properties", next); }
  function removeProperty(key: string) { const next = { ...(workflow?.properties || {}) }; delete next[key]; void action("update_properties", next); }
  return <section className="document-workflow"><div><button type="button" className={open ? "active" : ""} onClick={() => setOpen((value) => !value)}>◇ 屬性與審核</button></div>{open && <div className="collab-panel"><div className="workflow-head"><span className={`workflow-state ${workflow?.reviewState?.toLowerCase() || "draft"}`}>{workflow ? reviewLabels[workflow.reviewState] : "載入中"}</span>{workflow?.lockedAt && <span className="workflow-lock">🔒 {workflow.lockedBy?.name || "成員"} 鎖定中</span>}</div>{workflow && <><div className="workflow-properties">{Object.keys(workflow.properties).length ? Object.entries(workflow.properties).map(([key, value]) => <div key={key}><strong>{key}</strong><span>{value}</span>{canWrite && <button type="button" onClick={() => removeProperty(key)} aria-label={`移除 ${key}`}>×</button>}</div>) : <p className="hint">尚未設定頁面屬性。</p>}</div>{canWrite && <button type="button" onClick={editProperties}>＋ 新增／更新屬性</button>}<div className="workflow-actions">{canWrite && (!workflow.lockedAt || workflow.isLockedByMe || workflow.canManage) && <button type="button" onClick={() => void action(workflow.lockedAt ? "unlock" : "lock")}>{workflow.lockedAt ? "解除鎖定" : "鎖定文件"}</button>}{canWrite && workflow.reviewState !== "IN_REVIEW" && <button type="button" onClick={() => void action("request_review")}>送交審核</button>}{workflow.canManage && workflow.reviewState === "IN_REVIEW" && <><button type="button" className="collab-primary" onClick={() => void action("approve")}>核准</button><button type="button" onClick={() => void action("changes_requested")}>要求修改</button></>}</div><div className="backlink-list"><strong>反向連結</strong>{backlinks.length ? backlinks.map((link) => <a key={link.id} href={`/?project=${encodeURIComponent(projectId)}&document=${encodeURIComponent(link.id)}`}>↩ {link.icon} {link.title}</a>) : <p className="hint">尚無反向連結。於 Markdown 使用 [[目前頁面標題]] 即可建立可追蹤連結。</p>}</div></>}{notice && <p className="collab-notice">{notice}</p>}</div>}</section>;
}
