"use client";

import { useEffect, useState } from "react";
import type { TeamMember } from "@/components/team-management";

const roles = { OWNER: "擁有者", ADMIN: "管理員", EDITOR: "編輯者", VIEWER: "檢視者" };
const nameOf = (member: TeamMember) => member.nickname || member.user.name;

export function MemberSettings({ workspaceId, canManage, accountProvisioningEnabled, minimumPasswordLength, onMembersChange }: { workspaceId: string; canManage: boolean; accountProvisioningEnabled: boolean; minimumPasswordLength: number; onMembersChange: (members: TeamMember[]) => void }) {
  const [members, setMembers] = useState<TeamMember[]>([]); const [notice, setNotice] = useState(""); const [creating, setCreating] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", password: "", nickname: "", teamGroup: "", jobTitle: "", role: "VIEWER" as TeamMember["role"] });
  const reload = async () => { const response = await fetch(`/api/workspaces/${workspaceId}/members`); if (!response.ok) return; const next = await response.json() as TeamMember[]; setMembers(next); onMembersChange(next); };
  useEffect(() => { void reload(); }, [workspaceId]);
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setCreating(true); const response = await fetch(`/api/workspaces/${workspaceId}/accounts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, nickname: form.nickname || undefined, teamGroup: form.teamGroup || undefined, jobTitle: form.jobTitle || undefined }) }); const result = await response.json(); setCreating(false); if (!response.ok) return setNotice(result.error || "無法建立帳號"); setForm({ name: "", email: "", password: "", nickname: "", teamGroup: "", jobTitle: "", role: "VIEWER" }); setNotice("帳號已建立；請安全地將初始密碼交給該成員。"); await reload(); }
  async function update(member: TeamMember, fields: Partial<Pick<TeamMember, "nickname" | "teamGroup" | "jobTitle" | "role">>) { const response = await fetch(`/api/workspaces/${workspaceId}/members/${member.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(fields) }); const result = await response.json(); if (!response.ok) return setNotice(result.error || "無法更新成員"); setMembers((current) => { const next = current.map((item) => item.id === member.id ? result : item); onMembersChange(next); return next; }); setNotice("成員資料已儲存"); }
  async function remove(member: TeamMember) { if (!window.confirm(`確定要移除「${nameOf(member)}」嗎？`)) return; const response = await fetch(`/api/workspaces/${workspaceId}/members/${member.id}`, { method: "DELETE" }); if (!response.ok) return setNotice("無法移除成員"); const next = members.filter((item) => item.id !== member.id); setMembers(next); onMembersChange(next); }
  const options = Object.entries(roles).map(([value, label]) => <option key={value} value={value}>{label}</option>);
  const avatar = (member: TeamMember) => <div className="member-avatar">{member.user.avatarUrl ? <img src={member.user.avatarUrl} alt={`${nameOf(member)} 的頭像`} /> : member.user.avatarEmoji || nameOf(member).slice(0, 1).toUpperCase()}</div>;
  const edit = (member: TeamMember, key: "nickname" | "teamGroup" | "jobTitle") => <input defaultValue={member[key] || ""} placeholder={key === "nickname" ? "暱稱" : key === "teamGroup" ? "所屬分組" : "職位"} disabled={!canManage} onBlur={(event) => { const value = event.currentTarget.value.trim() || null; if (value !== member[key]) void update(member, { [key]: value }); }} />;
  return <section className="settings-members member-settings"><div><p className="eyebrow">團隊設定</p><h2>成員帳號、分組與職位</h2></div>{canManage && accountProvisioningEnabled && <section className="member-create-card"><h3>建立登入帳號</h3><form className="member-create-form" onSubmit={create}>{(["name", "email", "password", "nickname", "teamGroup", "jobTitle"] as const).map((key) => <input key={key} type={key === "email" ? "email" : key === "password" ? "password" : "text"} minLength={key === "password" ? minimumPasswordLength : undefined} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} placeholder={key === "name" ? "姓名" : key === "email" ? "電子郵件" : key === "password" ? `初始密碼（至少 ${minimumPasswordLength} 個字元）` : key === "nickname" ? "暱稱" : key === "teamGroup" ? "所屬分組" : "職位"} required={["name", "email", "password"].includes(key)} />)}<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as TeamMember["role"] })}>{options}</select><button type="submit" disabled={creating}>{creating ? "建立中…" : "建立帳號"}</button></form></section>}{canManage && !accountProvisioningEnabled && <p className="hint">網頁建立帳號已由安全設定停用。</p>}<div className="member-settings-list">{members.map((member) => <article key={member.id}>{avatar(member)}<div className="member-identity"><strong>{nameOf(member)}</strong><span>{member.user.name} · {member.user.email}</span></div>{edit(member, "nickname")}{edit(member, "teamGroup")}{edit(member, "jobTitle")}<select value={member.role} disabled={!canManage} onChange={(event) => void update(member, { role: event.target.value as TeamMember["role"] })}>{options}</select>{canManage && <button className="team-remove" onClick={() => void remove(member)}>移除</button>}</article>)}</div>{notice && <span className="collab-notice">{notice}</span>}</section>;
}
