"use client";

import { useEffect, useState } from "react";
import type { TeamMember } from "@/components/team-management";

const roleNames = { OWNER: "擁有者", ADMIN: "管理員", EDITOR: "編輯者", VIEWER: "檢視者" };
const displayName = (member: TeamMember) => member.nickname || member.user.name;

export function MemberSettings({ workspaceId, canManage, accountProvisioningEnabled, minimumPasswordLength, onMembersChange }: { workspaceId: string; canManage: boolean; accountProvisioningEnabled: boolean; minimumPasswordLength: number; onMembersChange: (members: TeamMember[]) => void }) {
  const [members, setMembers] = useState<TeamMember[]>([]); const [notice, setNotice] = useState(""); const [creating, setCreating] = useState(false);
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [nickname, setNickname] = useState(""); const [teamGroup, setTeamGroup] = useState(""); const [jobTitle, setJobTitle] = useState(""); const [role, setRole] = useState<TeamMember["role"]>("VIEWER");
  const reload = async () => { const response = await fetch(`/api/workspaces/${workspaceId}/members`); if (!response.ok) return; const next = await response.json() as TeamMember[]; setMembers(next); onMembersChange(next); };
  useEffect(() => { void reload(); }, [workspaceId]);
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setCreating(true); setNotice(""); const response = await fetch(`/api/workspaces/${workspaceId}/accounts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, email, password, nickname: nickname || undefined, teamGroup: teamGroup || undefined, jobTitle: jobTitle || undefined, role }) }); const result = await response.json(); setCreating(false); if (!response.ok) return setNotice(result.error || "無法建立帳號"); setName(""); setEmail(""); setPassword(""); setNickname(""); setTeamGroup(""); setJobTitle(""); setRole("VIEWER"); setNotice("帳號已建立；請安全地將初始密碼交給該成員。"); await reload(); }
  async function update(member: TeamMember, fields: Partial<Pick<TeamMember, "nickname" | "teamGroup" | "jobTitle" | "role">>) { const response = await fetch(`/api/workspaces/${workspaceId}/members/${member.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(fields) }); const result = await response.json(); if (!response.ok) return setNotice(result.error || "無法更新成員"); setMembers((current) => { const next = current.map((item) => item.id === member.id ? result : item); onMembersChange(next); return next; }); setNotice("成員資料已儲存"); }
  async function remove(member: TeamMember) { if (!window.confirm(`確定要移除「${displayName(member)}」嗎？`)) return; const response = await fetch(`/api/workspaces/${workspaceId}/members/${member.id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) return setNotice(result.error || "無法移除成員"); const next = members.filter((item) => item.id !== member.id); setMembers(next); onMembersChange(next); setNotice("成員已移除"); }
  const roleOptions = Object.entries(roleNames).map(([value, label]) => <option key={value} value={value}>{label}</option>);
  return <section className="settings-members member-settings"><div><p className="eyebrow">團隊設定</p><h2>成員帳號、分組與職位</h2></div>{canManage && accountProvisioningEnabled && <section className="member-create-card"><h3>建立登入帳號</h3><form className="member-create-form" onSubmit={create}><input value={name} onChange={(event) => setName(event.target.value)} placeholder="姓名" required /><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="電子郵件" required /><input type="password" minLength={minimumPasswordLength} value={password} onChange={(event) => setPassword(event.target.value)} placeholder={`初始密碼（至少 ${minimumPasswordLength} 個字元）`} required /><input value={nickname} onChange={(event) => setNickname(event.target.value)} placeholder="暱稱" /><input value={teamGroup} onChange={(event) => setTeamGroup(event.target.value)} placeholder="所屬分組，例如：飛行組" /><input value={jobTitle} onChange={(event) => setJobTitle(event.target.value)} placeholder="職位，例如：系統工程師" /><select value={role} onChange={(event) => setRole(event.target.value as TeamMember["role"])}>{roleOptions}</select><button type="submit" disabled={creating}>{creating ? "建立中…" : "建立帳號"}</button></form></section>}{canManage && !accountProvisioningEnabled && <p className="hint">網頁建立帳號已由安全設定停用。</p>}<div className="member-settings-list">{members.map((member) => <article key={member.id}><div className="member-avatar">{member.user.avatarEmoji || displayName(member).slice(0, 1).toUpperCase()}</div><div className="member-identity"><strong>{displayName(member)}</strong><span>{member.user.name} · {member.user.email}</span></div><input defaultValue={member.nickname || ""} placeholder="暱稱" disabled={!canManage} onBlur={(event) => { const value = event.currentTarget.value.trim() || null; if (value !== member.nickname) void update(member, { nickname: value }); }} /><input defaultValue={member.teamGroup || ""} placeholder="所屬分組" disabled={!canManage} onBlur={(event) => { const value = event.currentTarget.value.trim() || null; if (value !== member.teamGroup) void update(member, { teamGroup: value }); }} /><input defaultValue={member.jobTitle || ""} placeholder="職位" disabled={!canManage} onBlur={(event) => { const value = event.currentTarget.value.trim() || null; if (value !== member.jobTitle) void update(member, { jobTitle: value }); }} /><select value={member.role} disabled={!canManage} onChange={(event) => void update(member, { role: event.target.value as TeamMember["role"] })}>{roleOptions}</select>{canManage && <button className="team-remove" onClick={() => void remove(member)}>移除</button>}</article>)}</div>{notice && <span className="collab-notice">{notice}</span>}</section>;
}
