"use client";

import { useState } from "react";
import type { TeamMember } from "@/components/team-management";

export type ProjectModule = "tasks" | "issues" | "bom" | "tests";
export type ModuleRecord = { id: string; [key: string]: unknown };
const moduleText = { tasks: { title: "任務", hint: "安排工作、負責人、優先級與期限" }, issues: { title: "議題", hint: "追蹤風險、異常與處理狀態" }, bom: { title: "物料清單", hint: "管理料號、數量、供應商與採購狀態" }, tests: { title: "測試紀錄", hint: "記錄測試結果、日期、操作人與備註" } };
const displayMember = (member: TeamMember) => member.nickname || member.user.name;
const dateValue = (value: unknown) => value ? new Date(String(value)).toISOString().slice(0, 10) : "";

export function ProjectModuleBoard({ projectId, module, initialRecords, members, editable }: { projectId: string; module: ProjectModule; initialRecords: ModuleRecord[]; members: TeamMember[]; editable: boolean }) {
  const [records, setRecords] = useState(initialRecords); const [title, setTitle] = useState(""); const [notice, setNotice] = useState(""); const [editMode, setEditMode] = useState(false); const info = moduleText[module]; const canEdit = editable && editMode;
  async function request(path: string, method: "POST" | "PATCH" | "DELETE", body?: unknown) { const response = await fetch(path, { method, headers: body === undefined ? undefined : { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "儲存失敗"); return result as ModuleRecord; }
  async function create() { if (!title.trim()) return; try { const data = module === "tasks" ? { title: title.trim() } : module === "issues" ? { title: title.trim() } : module === "bom" ? { name: title.trim() } : { title: title.trim() }; const record = await request(`/api/projects/${projectId}/records/${module}`, "POST", data); setRecords((current) => [record, ...current]); setTitle(""); setNotice("已新增紀錄"); } catch (error) { setNotice(error instanceof Error ? error.message : "無法新增紀錄"); } }
  async function update(record: ModuleRecord, values: Record<string, unknown>) { try { const saved = await request(`/api/projects/${projectId}/records/${module}/${record.id}`, "PATCH", values); setRecords((current) => current.map((item) => item.id === record.id ? saved : item)); setNotice("已儲存"); } catch (error) { setNotice(error instanceof Error ? error.message : "變更尚未儲存"); } }
  async function remove(record: ModuleRecord) { if (!window.confirm("確定要刪除此紀錄嗎？此操作無法復原。")) return; try { await request(`/api/projects/${projectId}/records/${module}/${record.id}`, "DELETE"); setRecords((current) => current.filter((item) => item.id !== record.id)); setNotice("紀錄已刪除"); } catch (error) { setNotice(error instanceof Error ? error.message : "無法刪除紀錄"); } }
  const input = (record: ModuleRecord, field: string, type = "text") => <input className="module-cell-input" disabled={!canEdit} type={type} defaultValue={String(record[field] ?? "")} onBlur={(event) => { const value = type === "number" && field !== "unitCost" ? Number(event.currentTarget.value || 0) : event.currentTarget.value; if (String(record[field] ?? "") !== String(value)) void update(record, { [field]: value }); }} />;
  const select = (record: ModuleRecord, field: string, options: Array<[string, string]>) => <select className="module-cell-input" disabled={!canEdit} value={String(record[field] ?? "")} onChange={(event) => void update(record, { [field]: field === "priority" || field === "severity" ? Number(event.target.value) : event.target.value })}>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>;
  const removeButton = (record: ModuleRecord) => canEdit ? <button className="module-delete" onClick={() => void remove(record)}>刪除</button> : null;
  const table = module === "tasks" ? <div className="module-table task-module-table"><header><span>任務</span><span>狀態</span><span>優先級</span><span>開始</span><span>結束</span><span>負責人</span><span /></header>{records.map((record) => <article key={record.id}>{input(record, "title")}{select(record, "status", [["BACKLOG","待排程"],["TODO","待處理"],["IN_PROGRESS","進行中"],["BLOCKED","受阻"],["DONE","已完成"]])}{select(record, "priority", [["1","P1"],["2","P2"],["3","P3"],["4","P4"],["5","P5"]])}<input className="module-cell-input" disabled={!canEdit} type="date" value={dateValue(record.startDate)} onChange={(event) => void update(record, { startDate: event.target.value || null })}/><input className="module-cell-input" disabled={!canEdit} type="date" value={dateValue(record.dueDate)} onChange={(event) => void update(record, { dueDate: event.target.value || null })}/><select className="module-cell-input" disabled={!canEdit} value={String(record.assigneeId || "")} onChange={(event) => void update(record, { assigneeId: event.target.value || null })}><option value="">未指派</option>{members.map((member) => <option key={member.id} value={member.user.id}>{displayMember(member)}</option>)}</select>{removeButton(record)}</article>)}</div> : module === "issues" ? <div className="module-table"><header><span>編號</span><span>議題</span><span>狀態</span><span>嚴重度</span><span /></header>{records.map((record) => <article key={record.id}>{input(record, "key")}{input(record, "title")}{select(record, "status", [["OPEN","開啟"],["INVESTIGATING","調查中"],["RESOLVED","已解決"],["WONT_FIX","不處理"]])}{select(record, "severity", [["1","S1"],["2","S2"],["3","S3"],["4","S4"],["5","S5"]])}{removeButton(record)}</article>)}</div> : module === "bom" ? <div className="module-table"><header><span>料號</span><span>名稱</span><span>數量</span><span>供應商</span><span>狀態</span><span>單價</span><span /></header>{records.map((record) => <article key={record.id}>{input(record, "partNumber")}{input(record, "name")}{input(record, "quantity", "number")}{input(record, "supplier")}{input(record, "status")}{input(record, "unitCost", "number")}{removeButton(record)}</article>)}</div> : <div className="module-table"><header><span>測試名稱</span><span>結果</span><span>日期</span><span>操作人</span><span>備註</span><span /></header>{records.map((record) => <article key={record.id}>{input(record, "title")}{select(record, "outcome", [["PLANNED","計畫中"],["PASS","通過"],["FAIL","失敗"],["BLOCKED","受阻"]])}<input className="module-cell-input" disabled={!canEdit} type="date" value={dateValue(record.testDate)} onChange={(event) => void update(record, { testDate: event.target.value || null })}/>{input(record, "operator")}{input(record, "notes")}{removeButton(record)}</article>)}</div>;
  return <section className="module-view module-editor"><div className="module-hero"><div><p className="eyebrow">專案模組</p><h1>{info.title}</h1><p>{info.hint}</p></div><div className="module-hero-actions">{editable && <button className={canEdit ? "module-edit-toggle active" : "module-edit-toggle"} onClick={() => setEditMode((current) => !current)}>{canEdit ? "✓ 完成編輯" : "✎ 啟用編輯"}</button>}<span className="overview-badge">{records.length} 筆</span></div></div>{canEdit ? <form className="module-create" onSubmit={(event) => { event.preventDefault(); void create(); }}><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder={module === "bom" ? "新增物料名稱" : `新增${info.title}`} required /><button type="submit">＋ 新增</button></form> : <p className="module-locked-hint">{editable ? "目前為閱讀模式。按「啟用編輯」後才可新增、修改或刪除。" : "你目前為檢視者，只能閱讀此模組。"}</p>}{table}{!records.length && <div className="empty">尚無紀錄</div>}{notice && <span className="collab-notice">{notice}</span>}</section>;
}
