"use client";

import { useEffect, useMemo, useState } from "react";
import { signOut } from "next-auth/react";
import { CollaborativeEditor } from "@/components/collaborative-editor";
import type { DatabaseData } from "@/components/database-view";
import { WorkspaceSearch } from "@/components/workspace-search";
import { SettingsPanel } from "@/components/settings-panel";
import { TeamManagement, type TeamMember } from "@/components/team-management";
import { ProjectModuleBoard, type ModuleRecord } from "@/components/project-module-board";
import { GanttBoard } from "@/components/gantt-board";
import { DocumentRecycleBin } from "@/components/document-recycle-bin";
import { AiAssistant } from "@/components/ai-assistant";
import { DocumentTemplatePicker } from "@/components/document-template-picker";
import { MyWorkPanel, type MyTask } from "@/components/my-work-panel";
import { VersionStatus } from "@/components/version-status";

type DocumentItem = { id: string; title: string; icon: string; parentId: string | null; content?: Record<string, unknown>; markdown?: string | null; updatedAt: Date | string; position: number };
type RecordData = { tasks: Array<ModuleRecord & { title: string; status: string; priority: number; startDate: string | Date | null; dueDate: string | Date | null }>; issues: Array<ModuleRecord & { key: string; title: string; status: string; severity: number }>; bom: Array<ModuleRecord & { partNumber: string; name: string; quantity: number; status: string; unitCost: string | null }>; tests: Array<ModuleRecord & { title: string; outcome: string; operator: string | null }> };
type ModuleName = keyof RecordData;
type WorkspaceModule = ModuleName | "gantt";
type AppDialog = { title: string; description?: string; confirmLabel?: string; initialValue?: string; onConfirm?: (value: string) => void; destructive?: boolean };

const moduleLabels: Record<WorkspaceModule, string> = { tasks: "任務", gantt: "甘特圖", issues: "議題", bom: "物料清單", tests: "測試紀錄" };
const moduleIcons: Record<WorkspaceModule, string> = { tasks: "✓", gantt: "▤", issues: "!", bom: "◫", tests: "⌁" };

function DocumentTree({ documents, databases, activeId, activeDatabaseId, onSelect, onSelectDatabase, onCreateChild, onMove, onDuplicate, onDelete, onLoadMore, hasMore }: { documents: DocumentItem[]; databases: DatabaseData[]; activeId: string; activeDatabaseId: string; onSelect: (id: string) => void; onSelectDatabase: (id: string) => void; onCreateChild: (parentId: string) => void; onMove: (draggedId: string, targetId: string, placement: "before" | "after" | "inside") => void; onDuplicate: (id: string) => void; onDelete: (id: string) => void; onLoadMore: () => void; hasMore: boolean }) {
  const byParent = useMemo(() => documents.reduce<Record<string, DocumentItem[]>>((acc, item) => { const key = item.parentId || "root"; (acc[key] ||= []).push(item); return acc; }, {}), [documents]);
  const databasesByDocument = useMemo(() => databases.filter((database) => database.parentDocumentId).reduce<Record<string, DatabaseData[]>>((acc, database) => { (acc[database.parentDocumentId || ""] ||= []).push(database); return acc; }, {}), [databases]);
  const [collapsed, setCollapsed] = useState<Set<string>>(() => new Set()); const [draggedId, setDraggedId] = useState<string | null>(null); const [dropTarget, setDropTarget] = useState<string | null>(null); const [contextMenu, setContextMenu] = useState<{ id: string; x: number; y: number } | null>(null);
  const toggle = (id: string) => setCollapsed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const render = (parentId: string | null, depth = 0): React.ReactNode => (byParent[parentId || "root"] || []).map((item) => { const hasChildren = Boolean(byParent[item.id]?.length || databasesByDocument[item.id]?.length); return <div className="tree-item" key={item.id}><div className={`tree-row ${dropTarget === item.id ? "drag-target" : ""}`} draggable onContextMenu={(event) => { event.preventDefault(); setContextMenu({ id: item.id, x: event.clientX, y: event.clientY }); }} onDragStart={(event) => { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", item.id); setDraggedId(item.id); }} onDragEnd={() => { setDraggedId(null); setDropTarget(null); }} onDragOver={(event) => { if (draggedId && draggedId !== item.id) { event.preventDefault(); event.dataTransfer.dropEffect = "move"; setDropTarget(item.id); } }} onDragLeave={() => setDropTarget((current) => current === item.id ? null : current)} onDrop={(event) => { event.preventDefault(); const source = event.dataTransfer.getData("text/plain") || draggedId; if (!source || source === item.id) return; const rect = event.currentTarget.getBoundingClientRect(); const placement = event.clientY < rect.top + rect.height * .28 ? "before" : event.clientY > rect.bottom - rect.height * .28 ? "after" : "inside"; onMove(source, item.id, placement); setDraggedId(null); setDropTarget(null); }}><button className="tree-collapse" aria-label={hasChildren ? (collapsed.has(item.id) ? `展開 ${item.title}` : `摺疊 ${item.title}`) : "沒有子項目"} disabled={!hasChildren} onClick={() => toggle(item.id)}>{hasChildren ? (collapsed.has(item.id) ? "›" : "⌄") : "·"}</button><button className={activeId === item.id ? "active" : ""} onClick={() => onSelect(item.id)}><span className="tree-rail" style={{ marginLeft: depth * 14 }}>{item.icon || "📄"}</span><span>{item.title}</span></button><button className="tree-subpage" aria-label={`在 ${item.title} 下新增子頁面`} onClick={() => onCreateChild(item.id)}>＋</button></div>{!collapsed.has(item.id) && <>{render(item.id, depth + 1)}{(databasesByDocument[item.id] || []).map((database) => <button key={database.id} className={activeDatabaseId === database.id ? "tree-database active" : "tree-database"} style={{ paddingLeft: 31 + (depth + 1) * 14 }} onClick={() => onSelectDatabase(database.id)}><span>▦</span>{database.name}</button>)}</>}</div>; });
  return <nav className="tree" aria-label="文件樹" onClick={() => setContextMenu(null)}>{render(null)}{hasMore && <button className="tree-load-more" type="button" onClick={onLoadMore}>載入更多文件</button>}{contextMenu && <div className="tree-context-menu" role="menu" style={{ left: contextMenu.x, top: contextMenu.y }} onClick={(event) => event.stopPropagation()}><button onClick={() => { onDuplicate(contextMenu.id); setContextMenu(null); }}>⧉ 複製文件</button><button className="danger" onClick={() => { const document = documents.find((item) => item.id === contextMenu.id); if (document && window.confirm(`確定要刪除「${document.title}」嗎？`)) onDelete(contextMenu.id); setContextMenu(null); }}>⌫ 刪除文件</button></div>}</nav>;
}

export function WorkspaceShell({ user, workspace, workspaceId, workspaces, project, projects, documents: initialDocuments, nextDocumentCursor: initialNextDocumentCursor, initialActiveId, initialModule, initialSelectedTaskId, databases: initialDatabases, records, myTasks, teamMembers: initialTeamMembers }: { user: { id: string; name: string; role: string; avatarEmoji?: string | null; avatarUrl?: string | null }; workspace: string; workspaceId: string; workspaces: Array<{ id: string; name: string }>; project: { id: string; name: string; code: string }; projects: Array<{ id: string; name: string; code: string }>; documents: DocumentItem[]; nextDocumentCursor?: string | null; initialActiveId?: string; initialModule?: WorkspaceModule; initialSelectedTaskId?: string; databases: DatabaseData[]; records: RecordData; myTasks: MyTask[]; teamMembers: TeamMember[] }) {
  const [documents, setDocuments] = useState(initialDocuments); const [nextDocumentCursor, setNextDocumentCursor] = useState(initialNextDocumentCursor || null); const [databases, setDatabases] = useState(initialDatabases); const [activeId, setActiveId] = useState(initialActiveId || initialDocuments[0]?.id || ""); const [activeDatabaseId, setActiveDatabaseId] = useState(""); const [module, setModule] = useState<WorkspaceModule | null>(initialModule || null); const [selectedTaskId, setSelectedTaskId] = useState<string | null>(initialSelectedTaskId || null); const [projectRecords, setProjectRecords] = useState(records); const [personalTasks, setPersonalTasks] = useState(myTasks); const [showSettings, setShowSettings] = useState(false); const [showTeam, setShowTeam] = useState(false); const [showRecycle, setShowRecycle] = useState(false); const [showAi, setShowAi] = useState(false); const [templatePicker, setTemplatePicker] = useState(false); const [workspaceName, setWorkspaceName] = useState(workspace); const [projectDisplay, setProjectDisplay] = useState(project); const [teamMembers, setTeamMembers] = useState(initialTeamMembers); const [currentUser, setCurrentUser] = useState(user); const [dialog, setDialog] = useState<AppDialog | null>(null);
  useEffect(() => { setProjectRecords(records); setPersonalTasks(myTasks); setSelectedTaskId(initialSelectedTaskId || null); if (initialModule) setModule(initialModule); }, [records, myTasks, initialModule, initialSelectedTaskId]);
  useEffect(() => { let cancelled = false; void fetch("/api/my-tasks?take=50", { cache: "no-store" }).then(async (response) => response.ok ? response.json() as Promise<{ tasks: MyTask[] }> : null).then((result) => { if (!cancelled && result) setPersonalTasks(result.tasks); }); return () => { cancelled = true; }; }, []);
  useEffect(() => { const document = documents.find((item) => item.id === activeId); if (!document || document.content !== undefined) return; let cancelled = false; void fetch(`/api/documents/${document.id}`, { cache: "no-store" }).then(async (response) => response.ok ? response.json() as Promise<Pick<DocumentItem, "content" | "markdown">> : null).then((loaded) => { if (!cancelled && loaded) setDocuments((current) => current.map((item) => item.id === document.id ? { ...item, ...loaded } : item)); }); return () => { cancelled = true; }; }, [activeId, documents]);
  const active = documents.find((item) => item.id === activeId); const initials = currentUser.name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  const completedTasks = projectRecords.tasks.filter((task) => task.status === "DONE").length; const taskProgress = projectRecords.tasks.length ? Math.round((completedTasks / projectRecords.tasks.length) * 100) : 0; const activeIssues = projectRecords.issues.filter((issue) => issue.status !== "RESOLVED" && issue.status !== "WONT_FIX").length;
  const activeDatabase = databases.find((database) => database.id === activeDatabaseId);
  function syncTaskRecords(next: RecordData["tasks"]) {
    setProjectRecords((current) => ({ ...current, tasks: next }));
    setPersonalTasks((current) => [...current.filter((task) => task.projectId !== project.id), ...next.filter((task) => task.assigneeId === currentUser.id).map((task) => ({ id: task.id, title: task.title, status: task.status, priority: task.priority, dueDate: task.dueDate, updatedAt: task.updatedAt, dependencies: task.dependencies, projectId: project.id, projectName: project.name, projectCode: project.code }))]);
  }
  function handleModuleRecordsChange(name: ModuleName, next: ModuleRecord[]) {
    if (name === "tasks") return syncTaskRecords(next as RecordData["tasks"]);
    setProjectRecords((current) => ({ ...current, [name]: next }));
  }
  function handlePersonalTaskUpdated(task: MyTask) {
    setPersonalTasks((current) => current.map((item) => item.id === task.id ? task : item));
    if (task.projectId === project.id) setProjectRecords((current) => ({ ...current, tasks: current.tasks.map((item) => item.id === task.id ? { ...item, ...task } : item) }));
  }
  const notify = (title: string, description?: string) => setDialog({ title, description, confirmLabel: "知道了" });
  async function createDocument(title: string, parentId?: string, templateId?: string) {
    if (!title.trim()) return;
    const response = await fetch(`/api/projects/${project.id}/documents`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title.trim(), parentId: parentId || null, templateId: templateId || null }) });
    if (!response.ok) return notify("無法建立文件", "請確認你的編輯權限後再試一次。");
    const document = await response.json(); setDocuments((current) => [...current, document]); setActiveId(document.id); setActiveDatabaseId(""); setModule(null); setShowSettings(false); setShowTeam(false);
  }
  async function createDatabase(name: string, parentDocumentId?: string) {
    if (!name.trim()) return;
    const response = await fetch(`/api/projects/${project.id}/databases`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim(), parentDocumentId: parentDocumentId || null }) });
    if (!response.ok) return notify("無法建立資料庫", "請確認你的編輯權限後再試一次。"); const database = await response.json(); setDatabases((current) => [...current, database]); setActiveDatabaseId(database.id); setModule(null); setShowSettings(false); setShowTeam(false);
  }
  async function deleteDocument(id: string) {
    const response = await fetch(`/api/documents/${id}`, { method: "DELETE" }); if (!response.ok) return notify("無法刪除文件", "請確認你的編輯權限後再試一次。");
    const result = await response.json() as { removedIds: string[] }; setDocuments((current) => current.filter((document) => !result.removedIds.includes(document.id))); const next = documents.find((document) => !result.removedIds.includes(document.id)); setActiveId(next?.id || "");
  }
  async function duplicateDocument(id: string) {
    const response = await fetch(`/api/documents/${id}/duplicate`, { method: "POST" }); const result = await response.json();
    if (!response.ok) return notify("無法複製文件", result.error || "請確認你的編輯權限後再試一次。");
    setDocuments((current) => [...current, result]); setActiveId(result.id); setActiveDatabaseId(""); setModule(null); setShowSettings(false); setShowTeam(false);
  }
  async function moveDocument(draggedId: string, targetId: string, placement: "before" | "after" | "inside") {
    const dragged = documents.find((item) => item.id === draggedId); const target = documents.find((item) => item.id === targetId); if (!dragged || !target || draggedId === targetId) return;
    const parentId = placement === "inside" ? target.id : target.parentId; const siblings = documents.filter((item) => item.parentId === parentId && item.id !== draggedId).sort((a, b) => a.position - b.position); const targetIndex = placement === "inside" ? siblings.length : siblings.findIndex((item) => item.id === targetId) + (placement === "after" ? 1 : 0);
    const response = await fetch(`/api/documents/${draggedId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ parentId, position: Math.max(0, targetIndex) }) }); const result = await response.json();
    if (!response.ok) return notify("無法移動頁面", result.error || "請稍後再試。"); const moved = new Map((result.documents as Array<{ id: string; parentId: string | null; position: number }>).map((item) => [item.id, item])); setDocuments((current) => current.map((item) => moved.has(item.id) ? { ...item, ...moved.get(item.id) } : item));
  }
  const requestCreateDocument = (parentId?: string) => setDialog({ title: parentId ? "新增子頁面" : "新增頁面", description: "建立後可在文件內繼續編輯內容與設定圖標。", initialValue: "", confirmLabel: "建立頁面", onConfirm: (title) => void createDocument(title, parentId) });
  const requestCreateDatabase = (parentDocumentId?: string) => setDialog({ title: parentDocumentId ? "在此頁面下新增資料庫" : "新增資料庫", description: parentDocumentId ? "資料庫會與子頁面並列在目前文件下方。" : "資料庫可用於追蹤任務、物料、測試與自訂資料。", initialValue: "專案追蹤表", confirmLabel: "建立資料庫", onConfirm: (name) => void createDatabase(name, parentDocumentId) });
  const requestDeleteDocument = (id: string) => { const document = documents.find((item) => item.id === id); if (!document) return; setDialog({ title: "移至回收桶？", description: `「${document.title}」及其子頁面會移至回收桶，之後仍可還原。`, confirmLabel: "移至回收桶", destructive: true, onConfirm: () => void deleteDocument(id) }); };
  async function loadMoreDocuments() { if (!nextDocumentCursor) return; const response = await fetch(`/api/projects/${project.id}/documents?take=200&cursor=${encodeURIComponent(nextDocumentCursor)}`, { cache: "no-store" }); const result = await response.json() as { documents?: DocumentItem[]; nextCursor?: string | null }; if (!response.ok) return notify("無法載入更多文件", "請稍後再試。"); setDocuments((current) => [...current, ...(result.documents || [])]); setNextDocumentCursor(result.nextCursor || null); }
  return <div className="app">
    <aside className="sidebar">
      <div className="brand-lockup"><span className="rocket-mark"><i /> <i /> <i /></span><div><p className="brand">Rocket Workspace</p><span className="brand-subtitle">任務控制台</span></div></div>
      <section className="project-card"><div className="project-code"><span className="live-dot" />{projectDisplay.code}</div>{workspaces.length > 1 && <label><span className="sr-only">切換工作空間</span><select value={workspaceId} aria-label="切換工作空間" onChange={(event) => { window.location.assign(`/?workspace=${encodeURIComponent(event.target.value)}`); }}>{workspaces.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label><span className="sr-only">切換專案</span><select value={project.id} aria-label="切換專案" onChange={(event) => { window.location.assign(`/?workspace=${encodeURIComponent(workspaceId)}&project=${encodeURIComponent(event.target.value)}`); }}>{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><span>{workspace}</span></section>
      <div className="sidebar-create-actions"><button className="create-document" onClick={() => requestCreateDocument()}><span>＋</span> 新增頁面</button><button className="create-document template-create" onClick={() => setTemplatePicker(true)}><span>◇</span> 從模板建立</button></div>
      <div className="side-heading"><span>文件庫</span><span>{documents.length}</span></div>
      <DocumentTree documents={documents} databases={databases} activeId={activeId} activeDatabaseId={activeDatabaseId} onSelect={(id) => { setActiveId(id); setActiveDatabaseId(""); setModule(null); setShowSettings(false); setShowTeam(false); setShowRecycle(false); }} onSelectDatabase={(id) => { setActiveDatabaseId(id); setModule(null); setShowSettings(false); setShowTeam(false); setShowRecycle(false); }} onCreateChild={requestCreateDocument} onMove={moveDocument} onDuplicate={(id) => void duplicateDocument(id)} onDelete={requestDeleteDocument} onLoadMore={() => void loadMoreDocuments()} hasMore={Boolean(nextDocumentCursor)} />
      <div className="side-heading database-heading"><span>資料庫</span><span>{databases.length}</span></div>
      <nav className="database-nav" aria-label="資料庫">{databases.filter((database) => !database.parentDocumentId).map((database) => <button key={database.id} className={activeDatabaseId === database.id ? "active" : ""} onClick={() => { setActiveDatabaseId(database.id); setModule(null); setShowSettings(false); setShowTeam(false); }}><span>▦</span>{database.name}</button>)}</nav>
      <button className="create-database" onClick={() => requestCreateDatabase()}><span>＋</span> 新增資料庫</button>
      <button className={`workspace-settings-link sidebar-recycle-link ${showRecycle ? "active" : ""}`} onClick={() => { setShowRecycle(true); setShowSettings(false); setShowTeam(false); setModule(null); setActiveDatabaseId(""); }}>♻ 回收桶</button>
      <button className={`workspace-settings-link ${showTeam ? "active" : ""}`} onClick={() => { setShowTeam(true); setShowSettings(false); setModule(null); setActiveDatabaseId(""); }}>♙ 團隊成員</button>
      <button className={`workspace-settings-link ${showAi ? "active" : ""}`} onClick={() => { setShowAi(true); setShowSettings(false); setShowTeam(false); setShowRecycle(false); setModule(null); setActiveDatabaseId(""); }}>✦ AI 與整合</button>
      <button className={`workspace-settings-link ${showSettings ? "active" : ""}`} onClick={() => { setShowSettings(true); setShowAi(false); setShowTeam(false); setModule(null); setActiveDatabaseId(""); }}>⚙ 設定中心</button>
      <div className="sidebar-footer"><span className="safe-indicator" />ObserveOnly · 安全模式</div>
    </aside>
    <main className="main">
      <header className="topbar"><div className="breadcrumbs"><span>{workspaceName}</span><b>/</b><strong>{showSettings ? "設定中心" : showAi ? "AI 與整合" : showTeam ? "團隊成員" : showRecycle ? "回收桶" : module ? moduleLabels[module] : activeDatabase ? activeDatabase.name : active?.title || "文件"}</strong></div><div className="topbar-actions"><WorkspaceSearch projectId={project.id} onSelect={(result) => { setShowSettings(false); setShowAi(false); setShowTeam(false); setShowRecycle(false); setModule(null); if (result.type === "document") { setActiveId(result.id); setActiveDatabaseId(""); } else setActiveDatabaseId(result.id); }} /><button className="topbar-settings" aria-label="開啟設定中心" title="設定中心" onClick={() => { setShowSettings(true); setShowAi(false); setShowTeam(false); setShowRecycle(false); setModule(null); setActiveDatabaseId(""); }}>⚙</button><span className="sync-state"><i /> 即時同步中</span><span className="role-badge">{currentUser.role}</span><div className="avatar" title={currentUser.name}>{currentUser.avatarUrl ? <img src={currentUser.avatarUrl} alt="" /> : currentUser.avatarEmoji || initials}</div></div></header>
      {showSettings ? <SettingsPanel projectId={project.id} workspaceId={workspaceId} onIdentitySaved={({ workspaceName: nextWorkspace, projectName, projectCode }) => { setWorkspaceName(nextWorkspace); setProjectDisplay({ ...projectDisplay, name: projectName, code: projectCode }); }} onMembersChange={setTeamMembers} onProfileSaved={(profile) => setCurrentUser((current) => ({ ...current, ...profile }))} onProjectCreated={(id) => window.location.assign(`/?project=${encodeURIComponent(id)}`)} /> : showAi ? <AiAssistant projectId={project.id} /> : showTeam ? <TeamManagement workspaceId={workspaceId} /> : showRecycle ? <DocumentRecycleBin projectId={project.id} canWrite={currentUser.role !== "VIEWER"} onRestored={() => window.location.reload()} /> : module === "gantt" ? <GanttBoard projectId={project.id} initialTasks={projectRecords.tasks} editable={currentUser.role !== "VIEWER"} /> : module ? <ProjectModuleBoard projectId={project.id} module={module} initialRecords={projectRecords[module]} members={teamMembers} editable={currentUser.role !== "VIEWER"} initialSelectedId={module === "tasks" ? selectedTaskId : undefined} onSelectedIdChange={module === "tasks" ? setSelectedTaskId : undefined} onRecordsChange={(next) => handleModuleRecordsChange(module, next)} /> : active?.content ? <CollaborativeEditor key={active.id} projectId={project.id} document={{ ...active, content: active.content, markdown: active.markdown || null }} user={currentUser} editable={currentUser.role !== "VIEWER"} onCreateSubpage={requestCreateDocument} onCreateDatabase={requestCreateDatabase} onIconChange={(icon) => setDocuments((current) => current.map((item) => item.id === active.id ? { ...item, icon } : item))} onDelete={() => requestDeleteDocument(active.id)} /> : active ? <section className="document"><div className="empty">正在載入文件…</div></section> : <section className="document"><div className="empty">尚無文件</div></section>}
    </main>
    <DocumentTemplatePicker projectId={project.id} open={templatePicker} onClose={() => setTemplatePicker(false)} onCreate={(templateId, title) => { setTemplatePicker(false); void createDocument(title, undefined, templateId); }} />
    <aside className="rightbar">
      <section className="mission-panel"><div className="panel-label">任務整備度</div><div className="readiness-row"><div className="readiness-ring" style={{ "--progress": `${Math.max(taskProgress, 8)}%` } as React.CSSProperties}><span>{taskProgress}%</span></div><div><strong>工作空間運作正常</strong><p>文件、資料庫與協作服務已連線。</p></div></div><div className="readiness-foot"><span><i />ObserveOnly</span><span>v0.3 引擎</span></div></section>
      <MyWorkPanel tasks={personalTasks} editable={currentUser.role !== "VIEWER"} currentProjectId={project.id} onTaskUpdated={handlePersonalTaskUpdated} onOpenTask={(task) => { if (task.projectId !== project.id) return window.location.assign(`/?project=${encodeURIComponent(task.projectId)}&task=${encodeURIComponent(task.id)}`); setModule("tasks"); setSelectedTaskId(task.id || null); setActiveDatabaseId(""); setShowSettings(false); setShowTeam(false); setShowRecycle(false); }} />
      <section className="module-panel"><div className="panel-heading"><h2>專案模組</h2><span>即時</span></div><div className="module-list">{(Object.keys(moduleLabels) as WorkspaceModule[]).map((name) => <button key={name} className={`module ${module === name ? "active" : ""}`} onClick={() => { setModule(name); setSelectedTaskId(null); setActiveDatabaseId(""); setShowSettings(false); setShowTeam(false); }}><span className="module-icon">{moduleIcons[name]}</span><span className="module-name">{moduleLabels[name]}</span><span className="module-count">{name === "gantt" ? projectRecords.tasks.filter((task) => task.startDate && task.dueDate).length : projectRecords[name].length}</span></button>)}</div></section>
      <section className="signal-panel"><div className="panel-label">狀態訊號</div><div className="signal-row"><span>未解決議題</span><strong className={activeIssues ? "warning" : "good"}>{activeIssues}</strong></div><div className="signal-row"><span>測試紀錄</span><strong>{projectRecords.tests.length}</strong></div><div className="signal-row"><span>線上協作者</span><strong className="good">01</strong></div></section>
      <VersionStatus /><div className="account-row"><div className="avatar small">{currentUser.avatarUrl ? <img src={currentUser.avatarUrl} alt="" /> : currentUser.avatarEmoji || initials}</div><div><strong>{currentUser.name}</strong><span>{currentUser.role.toLowerCase()}</span></div><button className="logout" aria-label="登出" onClick={() => signOut({ callbackUrl: "/login" })}>↗</button></div>
    </aside>
    {dialog && <AppDialogView dialog={dialog} onClose={() => setDialog(null)} />}
  </div>;
}

function AppDialogView({ dialog, onClose }: { dialog: AppDialog; onClose: () => void }) {
  const [value, setValue] = useState(dialog.initialValue || ""); const needsValue = dialog.onConfirm && dialog.initialValue !== undefined;
  return <div className="app-dialog-backdrop" role="presentation" onMouseDown={onClose}><section className="app-dialog" role="dialog" aria-modal="true" aria-labelledby="app-dialog-title" onMouseDown={(event) => event.stopPropagation()}><p className="eyebrow">Rocket Workspace</p><h2 id="app-dialog-title">{dialog.title}</h2>{dialog.description && <p>{dialog.description}</p>}{needsValue && <label>名稱<input autoFocus value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && value.trim()) { dialog.onConfirm?.(value.trim()); onClose(); } }} /></label>}<footer><button type="button" className="dialog-secondary" onClick={onClose}>取消</button><button type="button" className={dialog.destructive ? "dialog-danger" : "dialog-primary"} disabled={needsValue && !value.trim()} onClick={() => { dialog.onConfirm?.(value.trim()); onClose(); }}>{dialog.confirmLabel || "關閉"}</button></footer></section></div>;
}
