import { NextResponse } from "next/server";
import { ApprovalStatus, TestStepStatus } from "@prisma/client";
import { z } from "zod";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { canWrite, projectAccess } from "@/lib/permissions";

const inputSchema = z.discriminatedUnion("action", [
  z.object({ action: z.literal("add_step"), instruction: z.string().trim().min(1).max(10_000), expected: z.string().trim().max(10_000).nullable().optional(), position: z.number().int().min(0).max(10_000).optional() }),
  z.object({ action: z.literal("update_step"), stepId: z.string().cuid(), actual: z.string().trim().max(10_000).nullable().optional(), status: z.nativeEnum(TestStepStatus).optional(), instruction: z.string().trim().min(1).max(10_000).optional(), expected: z.string().trim().max(10_000).nullable().optional() }),
  z.object({ action: z.literal("add_measurement"), name: z.string().trim().min(1).max(160), value: z.number().finite(), unit: z.string().trim().max(32).nullable().optional(), minimum: z.number().finite().nullable().optional(), maximum: z.number().finite().nullable().optional() }),
  z.object({ action: z.literal("link_requirement"), requirementId: z.string().cuid() }),
  z.object({ action: z.literal("sign"), status: z.enum(["APPROVED", "REJECTED"]), note: z.string().trim().max(2_000).nullable().optional() }),
]);
async function accessTest(userId: string, projectId: string, testId: string) { const access = await projectAccess(userId, projectId); const test = access ? await prisma.testRecord.findFirst({ where: { id: testId, projectId, deletedAt: null } }) : null; return { access, test }; }
export async function GET(_: Request, { params }: { params: Promise<{ id: string; testId: string }> }) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { id, testId } = await params; const { access, test } = await accessTest(session.user.id, id, testId); if (!access || !test) return NextResponse.json({ error: "Not found" }, { status: 404 }); return NextResponse.json(await prisma.testRecord.findUnique({ where: { id: testId }, include: { plan: true, steps: { orderBy: { position: "asc" } }, measurements: { orderBy: { createdAt: "asc" } }, approvals: { include: { reviewer: { select: { name: true } } }, orderBy: { createdAt: "desc" } }, requirements: { include: { requirement: true } }, attachments: { where: { deletedAt: null }, select: { id: true, filename: true, mimeType: true, size: true, createdAt: true } } } })); }
export async function POST(request: Request, { params }: { params: Promise<{ id: string; testId: string }> }) { const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { id, testId } = await params; const { access, test } = await accessTest(session.user.id, id, testId); if (!access || !test || !canWrite(access.membership.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const input = inputSchema.safeParse(await request.json().catch(() => null)); if (!input.success) return NextResponse.json({ error: "測試證據資料不正確" }, { status: 400 });
  if (input.data.action === "add_step") return NextResponse.json(await prisma.testStep.create({ data: { testRecordId: testId, instruction: input.data.instruction, expected: input.data.expected || null, position: input.data.position ?? await prisma.testStep.count({ where: { testRecordId: testId } }) } }), { status: 201 });
  if (input.data.action === "update_step") { const step = await prisma.testStep.findFirst({ where: { id: input.data.stepId, testRecordId: testId } }); if (!step) return NextResponse.json({ error: "Not found" }, { status: 404 }); return NextResponse.json(await prisma.testStep.update({ where: { id: step.id }, data: { actual: input.data.actual, status: input.data.status, instruction: input.data.instruction, expected: input.data.expected } })); }
  if (input.data.action === "add_measurement") { if (input.data.minimum !== null && input.data.maximum !== null && input.data.minimum !== undefined && input.data.maximum !== undefined && input.data.minimum > input.data.maximum) return NextResponse.json({ error: "量測範圍不正確" }, { status: 400 }); return NextResponse.json(await prisma.testMeasurement.create({ data: { testRecordId: testId, name: input.data.name, value: input.data.value, unit: input.data.unit || null, minimum: input.data.minimum ?? null, maximum: input.data.maximum ?? null } }), { status: 201 }); }
  if (input.data.action === "link_requirement") { const requirement = await prisma.requirement.findFirst({ where: { id: input.data.requirementId, projectId: id } }); if (!requirement) return NextResponse.json({ error: "需求不存在" }, { status: 400 }); await prisma.requirementVerification.upsert({ where: { requirementId_testRecordId: { requirementId: requirement.id, testRecordId: testId } }, update: {}, create: { requirementId: requirement.id, testRecordId: testId } }); return NextResponse.json({ ok: true }); }
  if (!(["OWNER", "ADMIN"] as string[]).includes(access.membership.role)) return NextResponse.json({ error: "只有管理員可簽核" }, { status: 403 }); const approval = await prisma.testApproval.create({ data: { testRecordId: testId, reviewerId: session.user.id, status: input.data.status as ApprovalStatus, note: input.data.note || null } }); return NextResponse.json(approval, { status: 201 });
}
