import { NextResponse } from "next/server";
import { ApprovalStatus, IssueStatus, PurchaseStatus, TaskStatus, TestOutcome } from "@prisma/client";
import { z } from "zod";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { canWrite, projectAccess } from "@/lib/permissions";
import { isRecurrenceRule } from "@/lib/task-automation";

const moduleSchema = z.enum(["tasks", "issues", "bom", "tests"]);
const pageSize = (value: string | null) => Math.min(100, Math.max(1, Number(value) || 50));
const dateValue = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional();
const taskSchema = z.object({ title: z.string().trim().min(1).max(180), status: z.nativeEnum(TaskStatus).optional(), priority: z.number().int().min(1).max(5).optional(), startDate: dateValue, dueDate: dateValue, assigneeId: z.string().cuid().nullable().optional(), parentId: z.string().cuid().nullable().optional(), milestone: z.boolean().optional(), recurrenceRule: z.string().trim().max(500).refine(isRecurrenceRule, "週期規則格式不正確").nullable().optional(), recurrenceAnchor: dateValue, slaDueAt: dateValue });
const issueSchema = z.object({ title: z.string().trim().min(1).max(180), key: z.string().trim().min(1).max(50).optional(), status: z.nativeEnum(IssueStatus).optional(), severity: z.number().int().min(1).max(5).optional() });
const bomSchema = z.object({ name: z.string().trim().min(1).max(180), partNumber: z.string().trim().min(1).max(80).optional(), quantity: z.number().int().min(1).max(1_000_000).optional(), supplier: z.string().trim().max(180).nullable().optional(), status: z.string().trim().min(1).max(60).optional(), unitCost: z.string().regex(/^\d+(\.\d{1,2})?$/).nullable().optional(), supplierPartNumber: z.string().trim().max(120).nullable().optional(), alternatives: z.array(z.string().trim().min(1).max(120)).max(40).optional(), inventoryQuantity: z.number().int().min(0).max(10_000_000).optional(), reorderPoint: z.number().int().min(0).max(10_000_000).nullable().optional(), currency: z.string().trim().regex(/^[A-Z]{3}$/).optional(), version: z.string().trim().max(80).nullable().optional(), approvalStatus: z.nativeEnum(ApprovalStatus).optional(), purchaseStatus: z.nativeEnum(PurchaseStatus).optional(), leadTimeDays: z.number().int().min(0).max(3_650).nullable().optional(), riskLevel: z.number().int().min(1).max(5).optional(), notes: z.string().trim().max(20_000).nullable().optional() });
const testSchema = z.object({ title: z.string().trim().min(1).max(180), outcome: z.nativeEnum(TestOutcome).optional(), testDate: dateValue, operator: z.string().trim().max(120).nullable().optional(), notes: z.string().trim().max(20_000).nullable().optional(), planId: z.string().cuid().nullable().optional() });

export async function GET(request: Request, { params }: { params: Promise<{ id: string; module: string }> }) {
  const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { id, module } = await params; const access = await projectAccess(session.user.id, id); const kind = moduleSchema.safeParse(module);
  if (!access || !kind.success) return NextResponse.json({ error: "Not found" }, { status: 404 });
  const url = new URL(request.url); const cursor = url.searchParams.get("cursor"); const take = pageSize(url.searchParams.get("take")); const pagination = { take: take + 1, ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}), orderBy: [{ createdAt: "desc" as const }, { id: "desc" as const }] };
  const data = kind.data === "tasks" ? await prisma.task.findMany({ where: { projectId: id, deletedAt: null }, include: { assignee: { select: { id: true, name: true, email: true } }, dependencies: { where: { dependsOn: { deletedAt: null } }, include: { dependsOn: { select: { id: true, title: true, status: true } } } } }, ...pagination }) : kind.data === "issues" ? await prisma.issue.findMany({ where: { projectId: id, deletedAt: null }, ...pagination }) : kind.data === "bom" ? await prisma.bomItem.findMany({ where: { projectId: id, deletedAt: null }, ...pagination }) : await prisma.testRecord.findMany({ where: { projectId: id, deletedAt: null }, ...pagination });
  return NextResponse.json({ records: data.slice(0, take), nextCursor: data.length > take ? data[take - 1].id : null });
}
export async function POST(request: Request, { params }: { params: Promise<{ id: string; module: string }> }) {
  const session = await auth(); if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { id, module } = await params; const access = await projectAccess(session.user.id, id); const kind = moduleSchema.safeParse(module);
  if (!access || !kind.success || !canWrite(access.membership.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const body = await request.json().catch(() => null);
  if (kind.data === "tasks") { const input = taskSchema.safeParse(body); if (!input.success || (input.data.startDate && input.data.dueDate && input.data.startDate > input.data.dueDate)) return NextResponse.json({ error: "任務日期不正確" }, { status: 400 }); if (input.data.assigneeId && !await prisma.membership.findFirst({ where: { userId: input.data.assigneeId, workspaceId: access.project.workspaceId } })) return NextResponse.json({ error: "負責人必須是工作空間成員" }, { status: 400 }); if (input.data.parentId && !await prisma.task.findFirst({ where: { id: input.data.parentId, projectId: id, deletedAt: null } })) return NextResponse.json({ error: "父任務不存在" }, { status: 400 }); return NextResponse.json(await prisma.task.create({ data: { projectId: id, ...input.data, startDate: input.data.startDate ? new Date(`${input.data.startDate}T00:00:00.000Z`) : null, dueDate: input.data.dueDate ? new Date(`${input.data.dueDate}T00:00:00.000Z`) : null, recurrenceAnchor: input.data.recurrenceAnchor ? new Date(`${input.data.recurrenceAnchor}T00:00:00.000Z`) : null, slaDueAt: input.data.slaDueAt ? new Date(`${input.data.slaDueAt}T00:00:00.000Z`) : null }, include: { assignee: { select: { id: true, name: true, email: true } } } }), { status: 201 }); }
  if (kind.data === "issues") { const input = issueSchema.safeParse(body); if (!input.success) return NextResponse.json({ error: "議題資料不正確" }, { status: 400 }); return NextResponse.json(await prisma.issue.create({ data: { projectId: id, title: input.data.title, key: input.data.key || `ISSUE-${Date.now()}`, status: input.data.status, severity: input.data.severity } }), { status: 201 }); }
  if (kind.data === "bom") { const input = bomSchema.safeParse(body); if (!input.success) return NextResponse.json({ error: "物料資料不正確" }, { status: 400 }); return NextResponse.json(await prisma.bomItem.create({ data: { projectId: id, ...input.data, partNumber: input.data.partNumber || `PART-${Date.now()}`, unitCost: input.data.unitCost || null } }), { status: 201 }); }
  const input = testSchema.safeParse(body); if (!input.success || (input.data.planId && !await prisma.testPlan.findFirst({ where: { id: input.data.planId, projectId: id } }))) return NextResponse.json({ error: "測試資料或測試計畫不正確" }, { status: 400 }); return NextResponse.json(await prisma.testRecord.create({ data: { projectId: id, ...input.data, testDate: input.data.testDate ? new Date(`${input.data.testDate}T00:00:00.000Z`) : null } }), { status: 201 });
}
